driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.5
    run_list: apt::default
  - name: fedora-24
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[rsync::default]
  - name: simple
    run_list:
      - recipe[fake::simple]
  - name: read-only
    run_list:
      - recipe[fake::read_only]
  - name: networking
    run_list:
      - recipe[fake::networking]
