name              'rsync'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs rsync'
version           '3.1.3'
source_url        'https://github.com/sous-chefs/rsync'
issues_url        'https://github.com/sous-chefs/rsync/issues'
chef_version      '>= 13'

supports 'amazon'
supports 'centos'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
